// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeZKC5AjSpJTfBsvYbhUM81rTWYTAAI2k',
    appId: '1:496387316748:web:d67f86ec5e4fc6a937e229',
    messagingSenderId: '496387316748',
    projectId: 'note-provider-1352e',
    authDomain: 'note-provider-1352e.firebaseapp.com',
    storageBucket: 'note-provider-1352e.appspot.com',
    measurementId: 'G-3CBXTBZJDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDacsnH5MUbHsxljMp07FTXV1JYeuF87Qs',
    appId: '1:496387316748:android:c0a1191fa7e4621637e229',
    messagingSenderId: '496387316748',
    projectId: 'note-provider-1352e',
    storageBucket: 'note-provider-1352e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc5BnzWKGqxFq02VKPhfrL9oRDC3iBIpg',
    appId: '1:496387316748:ios:3aba82098d6256ce37e229',
    messagingSenderId: '496387316748',
    projectId: 'note-provider-1352e',
    storageBucket: 'note-provider-1352e.appspot.com',
    iosBundleId: 'com.example.noteProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc5BnzWKGqxFq02VKPhfrL9oRDC3iBIpg',
    appId: '1:496387316748:ios:3aba82098d6256ce37e229',
    messagingSenderId: '496387316748',
    projectId: 'note-provider-1352e',
    storageBucket: 'note-provider-1352e.appspot.com',
    iosBundleId: 'com.example.noteProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeZKC5AjSpJTfBsvYbhUM81rTWYTAAI2k',
    appId: '1:496387316748:web:cc9d9ee7fe146c5537e229',
    messagingSenderId: '496387316748',
    projectId: 'note-provider-1352e',
    authDomain: 'note-provider-1352e.firebaseapp.com',
    storageBucket: 'note-provider-1352e.appspot.com',
    measurementId: 'G-421HF4YYPP',
  );
}
